add compile tests for Unix configure (Windows will follow)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -46,6 +46,8 @@ usage()
     exit    
 }
 
+CONFIG_LOG="$relpath/config.log"
+rm -rf "$CONFIG_LOG"
 echo "CONFIG += silent"  > config.in
 
 while [ "$#" -gt 0 ]; do
@@ -180,12 +182,59 @@ else
     echo "qmf_enabled = yes" >> config.in
 fi
 
-echo "Testing Qt installation..."
-if ! which qmake; then
-    echo >&2 "Cannot find 'qmake' in your PATH";
+echo "Configuring Qt Mobility"
+echo 
+
+WHICH="$relpath/config.tests/tools/which.test"
+
+echo -n "Checking available Qt"
+if ! "$WHICH" qmake 2>/dev/null 1>&2; then
+    echo -en >&2 " ... Not found\n\n" 
+    echo >&2 "Cannot find 'qmake' in your PATH.";
+    echo >&2 "Aborting." 
+else
+    echo -en " ... "
+    qmake -query QT_VERSION
+fi
+
+# find out which make we want to use
+MAKE=
+for m in make gmake; do
+    if "$WHICH" $m >/dev/null 2>&1; then
+        MAKE=`$WHICH $m`
+        break
+    fi
+done
+if [ -z "$MAKE" ]; then
+    echo >&2 "Cannot find 'make' or 'gmake' in your PATH";
     echo >&2 "Aborting." 
 fi
 
+compileTest()
+{
+    echo -en "Checking $1"
+    CURRENT_PWD=`pwd`
+    cd "$relpath/config.tests/$2"
+    rm -rf ./$2
+    qmake >> "$CONFIG_LOG"
+    echo  -n " ."
+    "$MAKE" clean >> "$CONFIG_LOG"
+    echo -n "."
+    "$MAKE" >> "$CONFIG_LOG" 2>&1
+    echo -n ". "
+    if ./$2 >> "$CONFIG_LOG" 2>&1; then
+        echo "OK"
+    else
+        echo "No Found"
+    fi
+    cd "$CURRENT_PWD"
+}
+
+compileTest QMF qmf
+compileTest NetworkManager networkmanager
+
+
+exit 1
 echo "Generating Mobility Headers..."
 #remove old headers
 rm -rf $relpath/include
