make this build and work with mac and frameworks.
also being able to specify which mac sdk to build against.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -59,6 +59,9 @@ RELEASEMODE=
 CONTACTS_PLUGIN=
 LINUX_TARGET=
 QMAKE_CACHE="$shadowpath/.qmake.cache"
+LIB_PATH="lib"
+BIN_PATH="bin"
+MAC_SDK=
 
 usage() 
 {
@@ -89,6 +92,9 @@ usage()
     echo "                    options: symbian, wince, memory, maemo"
     echo "-maemo ............ Build Qt Mobility for Maemo."
     echo "                    (default: Desktop Linux)"
+    echo "-sdk <sdk>..........Build using Apple provided SDK <path/to/sdk>."
+    echo "                    example: -sdk /Developer/SDKs/MacOSX10.6.sdk"
+    echo
     
     rm -f "$CONFIG_IN"
     exit    
@@ -139,6 +145,10 @@ while [ "$#" -gt 0 ]; do
         -maemo)
             LINUX_TARGET=maemo 
             ;;
+        -sdk)
+            MAC_SDK="$2"
+            shift
+            ;;
         *)
             echo "Unknown option: $1"
             usage
@@ -146,6 +156,39 @@ while [ "$#" -gt 0 ]; do
     esac
     shift
 done
+
+echo "Configuring Qt Mobility"
+echo 
+
+WHICH="$relpath/config.tests/tools/which.test"
+
+printf "Checking available Qt"
+if ! "$WHICH" qmake 2>/dev/null 1>&2; then
+    printf " ... Not found\n\n" >&2
+    echo >&2 "Cannot find 'qmake' in your PATH.";
+    echo >&2 "Aborting." 
+else
+    printf " ... "
+    qmake -query QT_VERSION
+fi
+
+
+findframeworks()
+{
+# figure out if Qt was built with frameworks
+# if so, install in the correct place.
+# and fix rpath
+    echo "contains(QT_CONFIG,qt_framework):message(1)" > 1.pro
+    SOMETHING=`qmake 1.pro 2>&1`
+        if [ "$SOMETHING" = "Project MESSAGE: 1" ]; then
+            LIB_PATH="Library/Frameworks"
+            BIN_PATH="Applications"
+        fi
+    rm 1.pro
+}
+
+findframeworks
+
 
 if [ -z "$RELEASEMODE" ]; then
     RELEASEMODE="debug"
@@ -185,7 +228,7 @@ echo "QT_MOBILITY_INCLUDE = $QT_MOBILITY_INCLUDE" >> "$CONFIG_IN"
 
 #process library path
 if [ -z "$QT_MOBILITY_LIB" ]; then
-    QT_MOBILITY_LIB="$QT_MOBILITY_PREFIX/lib"
+    QT_MOBILITY_LIB="$QT_MOBILITY_PREFIX/$LIB_PATH"
 elif [ -d "$QT_MOBILITY_LIB" ]; then
     QT_MOBILITY_LIB=`(cd "$QT_MOBILITY_LIB"; /bin/pwd)`
 else
@@ -198,7 +241,7 @@ echo "QT_MOBILITY_LIB = $QT_MOBILITY_LIB" >> "$CONFIG_IN"
 
 #process binary path
 if [ -z "$QT_MOBILITY_BIN" ]; then
-    QT_MOBILITY_BIN="$QT_MOBILITY_PREFIX/bin"
+    QT_MOBILITY_BIN="$QT_MOBILITY_PREFIX/$BIN_PATH"
 elif [ -d "$QT_MOBILITY_BIN" ]; then
     QT_MOBILITY_BIN=`(cd "$QT_MOBILITY_BIN"; /bin/pwd)`
 else
@@ -212,6 +255,11 @@ echo "QT_MOBILITY_BIN = $QT_MOBILITY_BIN" >> "$CONFIG_IN"
 echo "QT_MOBILITY_SOURCE_TREE = $relpath" >> "$QMAKE_CACHE"
 echo "QT_MOBILITY_BUILD_TREE = $shadowpath" >> "$QMAKE_CACHE"
 
+if [ -n "$MAC_SDK" ]; then
+    QMAKE_MAC_SDK="$MAC_SDK"
+   echo "QMAKE_MAC_SDK = $QMAKE_MAC_SDK" >> "$CONFIG_IN"
+fi
+
 if [ -z "$BUILD_UNITTESTS" ]; then
     echo "build_unit_tests = no" >> "$CONFIG_IN"
 else
@@ -224,20 +272,6 @@ else
     echo "build_examples = yes" >> "$CONFIG_IN"
 fi
 
-echo "Configuring Qt Mobility"
-echo 
-
-WHICH="$relpath/config.tests/tools/which.test"
-
-printf "Checking available Qt"
-if ! "$WHICH" qmake 2>/dev/null 1>&2; then
-    printf " ... Not found\n\n" >&2
-    echo >&2 "Cannot find 'qmake' in your PATH.";
-    echo >&2 "Aborting." 
-else
-    printf " ... "
-    qmake -query QT_VERSION
-fi
 
 # find out which make we want to use
 MAKE=
